daemon:
  interval: 1m
  concurrency: 1
  timeout: 15s
  initial: true

tasks:
  - name: wan
    getters:
      - type: asus
        address: 192.168.1.1
        username: asus
        password: asus
    handlers:
      - shell: 
          command: echo --- $IP ---
  - name: local
    getters:
      - type: ifconfig
        name: eno1
    handlers:
      - shell: 
          command: echo --- $IP ---
