daemon:
  interval: 1m
  concurrency: 1
  timeout: 15s
  initial: true

tasks:
  - name: wg
    getters:
      - type: domain
        domain: home.twofei.com
    handlers:
      - shell: 
          command: echo --- $IP ---
