daemon:
  interval: 1m
  concurrency: 1
  timeout: 15s
  initial: true

tasks:
  - name: wg
    getters:
      - type: domain
        domain: home.twofei.com
    handlers:
      - shell: 
          command: echo --- $IP ---
      - http:
          endpoint: https://api.chanify.net/v1/sender/CNiJhtUGEiJBRE5RRDY1VUFQRklXM1dNWUZTR0JBV0NWVElETlZHTDVJGhQBEFReB7e0AGspZ7PQtgBnmb_iTiIECAEQAQ.wGlSSBG4SW9LUfe9fiTbNmKozCUnIFxKmGe-pEtkhHk
          method: POST
          headers:
            content-type: text/plain
          body: $IP
